version: "3.9"
services: 
    nodeserver:
      build:
          context: ./app
      ports:
          - "5000:5000"
    nginx:
      restart: always
      build:
          context: ./nginx
      ports:
          - "81:81"
